import { generateRandomColor } from "@/shared/lib/color";
import type { Shape } from "./dto";

export const shapes: Shape[] = [
  {
    id: "1",
    x: 250,
    y: 250,
    width: 250,
    height: 125,
    type: "rectangle",
    sketch: false,
    colorId: generateRandomColor(),
  },
  // {
  //   id: "2",
  //   x: 120,
  //   y: 120,
  //   width: 100,
  //   height: 100,
  //   type: "rectangle",
  //   sketch: true,
  //   colorId: generateRandomColor(),
  // },
  {
    id: "3",
    x: 100,
    y: -200,
    width: 250,
    height: 100,
    type: "rectangle",
    sketch: true,
    colorId: generateRandomColor(),
  },
  {
    id: "7",
    x: 0,
    y: 0,
    width: 200,
    height: 200,
    sketch: true,
    type: "circle",
    colorId: generateRandomColor(),
  },
  {
    id: "4",
    x: -250,
    y: -300,
    width: 100,
    height: 100,
    type: "rectangle",
    sketch: false,
    colorId: generateRandomColor(),
  },
  {
    id: "5",
    x: 320,
    y: 2000,
    width: 100,
    height: 70,
    type: "rectangle",
    sketch: false,
    colorId: generateRandomColor(),
  },
  {
    id: "6",
    x: 3200,
    y: 400,
    width: 100,
    height: 70,
    type: "rectangle",
    sketch: false,
    colorId: generateRandomColor(),
  }
]

